### ISSUE TITLE
Some ideas to improve the app

### ISSUE THREAD

**Issue by maximilianmeier** [egosapien/T-Minus#1]
## Sound when finished
A sound would be nice to be notified when the countdown is done. This is useful for short countdowns. 

## Move app to the foreground
When the countdown is done the app could be displayed in the foreground of all apps so that the user sees that the countdown is done even without sound on.

## Hide days
Maybe just show countdown elements that are necessary for displaying the countdown

**Comment by stonehouse** [comment]
Congrats on being first 👏. So, what kind of use cases do you see for the app? I'm just trying to gather some ideas to think about what kind of experience and what kind of features I should build.

So far, I'm thinking: counting down to holidays or special occasion, or having a constant reminder of an important deadline that's looming.

**Comment by maximilianmeier** [comment]
Today I used the app to keep on track with learning for exams and to be reminded to take a break. For that the time period was rather short 30 minutes to 2 hours.

**Comment by stonehouse** [comment]
I'm still going to clean up the presentation of the days. There's still some issues like showing 4:3 instead of 4:03 etc., but I thought it was nice having the pop to foreground and sound effect.
